[package]
name = "rating-stats-per-game"
version = "0.1.0"
authors = ["Martin Colwell <colwem@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pgn-reader = "0.15.0"
histogram = "0.6.9"
